---
title: "Award winners"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Loading various libraries
```{r loads, include=FALSE}
library(rvest)
library(tidyverse)
```


```{r}
#Define a function to automate extracts MVP winners
#input parameter _x_ is a URL to be scraped
url_reads <- function(x) {
  #declare result as returned dataframe 
  result <- x %>% 
    read_html() %>% #read the url string to HTML
    html_elements('table') %>% #read the elements with reference table
    html_table() #create table
  
  #result was saved as a list with dataframe at index1
  result <- result[[1]]
  
  result #return the result dataframe from URL _x_
}
```


#MVP
```{r}

#list of URLS for MVP tables
MVP <- str_c("https://www.baseball-reference.com/awards/mvp.shtml")

#create new dataframe of all years extracted using map_df to specify vector or URLs and function (url_reads) to apply
MVP_Table <- map_df(MVP, url_reads)
```


```{R extract_batting}
#extracting MVP winners
write_csv2(MVP_Table, here::here('MVP1960_2020'))

```


```{r}
#Define a function to automate extracts for Cy Young Winners
#input parameter _x_ is a URL to be scraped
url_reads <- function(x) {
  #declare result as returned dataframe 
  result <- x %>% 
    read_html() %>% #read the url string to HTML
    html_elements('table') %>% #read the elements with reference table
    html_table() #create table
  
  #result was saved as a list with dataframe at index1
  result <- result[[1]]
  
  result #return the result dataframe from URL _x_
}
```


#CY Young
```{r}
#numrow <- as.character(c(1:162))

#list of URLS for CY tables
CY <- str_c("https://www.baseball-reference.com/awards/cya.shtml")

#create new dataframe of all years extracted using map_df to specify vector or URLs and function (url_reads) to apply
CY_Table <- map_df(CY, url_reads)
```


```{R extract_batting}
#extracting CY Young Winners
write_csv2(CY_Table, here::here('CY1960_2020'))

```

```{r}
#Define a function to automate extracts for Cy Young Winners
#input parameter _x_ is a URL to be scraped
url_reads <- function(x) {
  #declare result as returned dataframe 
  result <- x %>% 
    read_html() %>% #read the url string to HTML
    html_elements('table') %>% #read the elements with reference table
    html_table() #create table
  
  #result was saved as a list with dataframe at index1
  result <- result[[1]]
  
  result #return the result dataframe from URL _x_
}
```


#Rookie of the Year
```{r}
#numrow <- as.character(c(1:162))

#list of URLS for Rookie of the year tables
Rook <- str_c("https://www.baseball-reference.com/awards/roy.shtml")

#create new dataframe of all years extracted using map_df to specify vector or URLs and function (url_reads) to apply
Rook_Table <- map_df(Rook, url_reads)
```


```{R extract_batting}
#extracting Rookie of the year winners
write_csv2(Rook_Table, here::here('Rookie1960_2020'))

```