---
title: "Exploring Data"
author: "Aaron Simot"
date: "10/25/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = FALSE}
library(tidyverse)
library(reactable)
library(paletteer)
library(vtable)
```


```{r load_data, message = FALSE, include=FALSE}
teamsBat <- read_csv2(here::here("data_dump/cleanTeamsBat1900_2020"))
teamsPitch <- read_csv2(here::here("data_dump/cleanTeamsPitch1900_2020"))
playerBat <- read_csv2(here::here("data_dump/cleanPlayerBat1960_2020"))
playerPitch <- read_csv2(here::here("data_dump/cleanPlayerPitch1960_2020"))
cyyoung <- read_csv2(here::here("data_dump/CYClean1960_2020"))
mvp <- read_csv2(here::here("data_dump/MVPClean1960_2020"))
rook <- read_csv2(here::here("data_dump/RookieClean1960_2020"))

```

Summary Table for Batting Players
```{r}
sumtable(data = playerBat,
   vars = c("G", "HR", "RBI", "AVG", "1B", "2B", "3B"),
   title = "Summary Statistics for Batters in MLB",
   note = "Data for 1960-2020",
   summ = c("notNA(x)", "mean(x)", "median(x)", "min(x)", "max(x)"),
   summ.names = c("Observations", "Mean", "Median", "Min", "Max"),
   labels = c("Games Played", "Home Runs", "Runs Batted In", "Batting Average", 
              "Singles Hit", "Doubles Hit", "Triples Hit"))

```


```{r message = FALSE}


playerBat %>%
  group_by(Season) %>%
  summarise(batAvg = mean(HR)) %>%
  ggplot(mapping = aes(x = Season, y = batAvg)) + 
  geom_point()

```


```{r mvpBAdistrib, message=FALSE}
# Plotting BA distribution for MVP Awardees
mvp %>%
  # Removing pitchers from displayed data
  filter(is.na(ERA)) %>%
  ggplot(mapping = aes(x = BA)) + 
  geom_histogram(binwidth = 0.005, color = "black", fill = "blue") + 
  geom_density(color = "red") + 
  labs(
    title = "Batting Averages of MVP Winners",
    subtitle = "1960 to 2020",
    caption = "*Excludes Pitchers"
  ) +
  xlab("Batting Average") + 
  ylab("Count")

```



```{r}
mvp %>% filter(BA > 0.3) %>% arrange(desc(BA))

```



```{r}

teamsBat
teamsPitch
playerBat
playerPitch

```


```{r}

reactable(playerBat,
          defaultColDef = colDef(align = "center"),
          sortable = TRUE,
          resizable = TRUE,
          filterable = TRUE,
          searchable = TRUE,
          pagination = TRUE,
          defaultSorted = c("Season", "Name")
)


```







